safe:        true
auto:        true
server:      true
baseurl:     /

future:      true
lsi:         false
pygments:    true
markdown:    rdiscount

source:      .
destination: ./_site
plugins:     ./_plugins

permalink: /:year/:month/:title

## Variables
title : plafer
description :
url : http://plafer.info
tagline :
author :
  name : c4605
  email : bolasblack@gmail.com
  github : bolasblack
  disqus : plaferinfo
  twitter : c4605
  feedburner : plafer

production_url : http://plafer.info
